# 5.4. 예외 처리

# 5.4.1. 오류 예시

- FileNotFoundError
    - 디렉터리 안에 없는 파일을 열려고 시도했을 때 발생하는 오류
    
- ZeroDivisionError
    - 0으로 다른 숫자를 나누는 경우 발생하는 오류
    
- indexError
    - 해당 리스트에서 얻을 수 없는 값일 때 발생하는 오류
    

# 5.4.2. 오류 예외 처리 기법

- try, except문
    - 기본 구조
        - `try`, `except`만 쓰는 방법 : `try` 아래 문장을 수행 중, 오류가 발생하면 `except` 아래 문장이 수행
            
            ```python
            try:
            	...
            except:
            	...
            ```
            
        - 발생 오류만 포함한 `except`문 : `try` 아래 문장을 수행 중, `[발생 오류]`에 해당하는 오류가 발생하면 `except` 아래 문장이 수행
            
            ```python
            try:
            	...
            except 발생 오류:
            	...
            ```
            
        - 발생 오류와 오류 메시지 변수까지 포함한 `except`문 : 위의 경우에서 오류 메시지의 내용까지 알고 싶을 때 사용하는 방법
            
            ```python
            try:
            	...
            except 발생 오류 as 오류 메시지 변수:
            	...
            ```
            
    - finally
        - `try`문에는 `finally`절을 사용할 수 있다. 예외 발생 여부에 상관없이 항상 수행된다.
        - 예로 사용한 리소스를 닫을 때, 아래와 같다.
            
            ```python
            f = open('foo.txt', 'w')
            try:
                # 무언가를 수행한다.
            finally:
                f.close()
            ```
            
    - 여러 개의 오류 처리하기
        - `except`문을 여러 번 사용한다.
            
            ```python
            try:
                ...
            except 발생 오류1:
               ... 
            except 발생 오류2:
               ...
            ```
            
        - 또는 소괄호로 묶어 한 줄로 입력한다.
            
            ```python
            try:
                a = [1,2]
                print(a[3])
                4/0
            except (ZeroDivisionError, IndexError) as e:
                print(e)
            ```
            
    - try문에 else절 사용하기
        - `try`문의 문장을 수행한 뒤 오류가 발생하지 않은 경우에만 `else`절의 문장을 수행한다.
            
            ```python
            try:
                age=int(input('나이를 입력하세요: '))
            except:
                print('입력이 정확하지 않습니다.')
            else:
                if age <= 18:
                    print('미성년자는 출입금지입니다.')
                else:
                    print('환영합니다.')
            
            # 입력값이 숫자가 아니라면 except문의 문장이 수행되고,
            # 숫자라면 else절의 문장이 수행된다.
            ```
            

# 5.4.3. 오류 회피 및 강제 발생

- 오류 회피
    - `except`문에 `pass`를 사용한다.
        
        ```python
        try:
            f = open("나없는파일", 'r')
        except FileNotFoundError:
            pass
        ```
        
- 오류 일부러 발생시키기
    - `raise` 명령어를 사용해 오류를 강제로 발생시킨다.
    - 예로, 프로그래밍 시 꼭 작성해야 하는 부분이 구현되지 않았을 때 일부러 오류를 일으킬 수 있다.
        
        ```python
        class Bird:
            def fly(self):
                raise NotImplementedError
        
        class Eagle(Bird):
            pass
        
        eagle = Eagle()
        eagle.fly()
        
        # Eagle 클래스에서 fly함수를 정의하지 않았기 때문에 해당 오류가 발생
        ```
        
    

# 5.4.4. __str__ 메서드

- `except 오류명 as 오류 메시지`를 통해 오류 메시지를 정상적으로 출력하기 위해서는, `__str__` 메서드를 구현해야한다.
    
    ```python
    class MyError(Exception): # 예외를 직접 만들 경우, 내장 클래스인 Exception 클래스를 상속한다.
        def __str__(self):
            return "허용되지 않는 별명입니다."
    
    def say_nick(nick):
        if nick == '바보':
            raise MyError()
        print(nick)
    
    try:
        say_nick("천사")
        say_nick("바보")
    except MyError as e:
        print(e) # 정상적으로 '허용되지 않는 별명입니다.' 출력
    ```